version: '3.7'
services:
  proxy:
    image: traefik:alpine
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    #labels:
    #  - "traefik.frontend.rule=Host:monitor.local"
    #  - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #  - type: bind
    #    source: /var/run/docker.sock
    #    target: /var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
    #  - target: 80
    #    published: 80
    #    protocol: tcp
    #    mode: host

  movies:
    build: ./movies
    image: pruebaa/movies
    labels:
      - "traefik.backend=movies"
      - "traefik.frontend.rule=Host:movies.local"